#!/bin/bash

echo "Are you cool?"
read cool

# [[ $cool == "yes" || $cool == "YES" || $cool == "Yes" || $cool == "Y"  ]]


if [[ $cool =~ Yes|YES|Y|y|yes ]]
then 
	echo "You are cool"
else
	echo "Well, will make cool"

fi
